- .github/workflows/npm-audit-fix.yml
- README.md
> ci(actions): create npm-audit-fix.yml

- dist/index.js
- lib/__tests__/npmArgs.test.js
- lib/audit.js
- lib/auditFix.js
- lib/index.js
- lib/npmArgs.js
- lib/updateNpm.js
`npm config set` is explicit, so it may be confusing.
> fix: replace `npm config set` with direct CLI options

- dist/index.js
- lib/updateNpm.js
https://github.com/ybiquitous/npm-audit-fix-action/runs/471216132?check_suite_focus=true#step:2:27
```
┌──────────────────────────────────────────────────────────┐
│                 npm update check failed                  │
│           Try running with sudo or get access            │
│           to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /home/runner/.config │
└──────────────────────────────────────────────────────────┘
```
> fix: error "npm update check failed"

- dist/index.js
- lib/index.js
> fix: check a file change

- dist/index.js
- lib/index.js
> The process '/usr/bin/git' failed with exit code 1
https://github.com/ybiquitous/npm-audit-fix-action/runs/491686793#step:3:130
> fix: handle `git diff` exit code

- dist/index.js
- lib/__tests__/auditFix.json
- lib/__tests__/buildPullRequestBody.test.js
- lib/buildPullRequestBody.js
- lib/index.js
- lib/packageRepoUrls.js
- package-lock.json
- package.json
Using by added [hosted-git-info](https://www.npmjs.com/package/hosted-git-info).
> feat: add repo lint for package

- dist/index.js
- lib/updateNpm.js
- package.json
https://github.com/npm/cli/releases/tag/v6.14.2
> fix: bump npm from 6.14.1 to 6.14.2

- dist/index.js
- lib/updateNpm.js
- package.json
https://github.com/npm/cli/releases/tag/v6.14.3
> fix: bump npm from 6.14.2 to 6.14.3

- dist/index.js
- lib/packageRepoUrls.js
https://github.com/ybiquitous/homepage/runs/526170913#step:3:4133
> Cannot read property 'browse' of undefined
> fix: consider no repository URL

- dist/index.js
- lib/updateNpm.js
- package.json
https://github.com/npm/cli/releases/tag/v6.14.4
> fix: bump npm from 6.14.3 to 6.14.4

- dist/index.js
- lib/updateNpm.js
- package.json
https://github.com/npm/cli/releases/tag/v6.14.5
> fix: bump npm from 6.14.4 to 6.14.5

- .github/workflows/commitlint.yml
https://github.com/wagoid/commitlint-github-action
> ci: run commitlint

- README.md
- action.yml
This adds a prefix `npm-audit-fix-action/` to reduce the possibility of branch name conflict.
> feat: change default `branch`

- dist/index.js
- lib/__tests__/buildPullRequestBody.test.js
- lib/buildPullRequestBody.js
- lib/constants.js
- lib/npmArgs.js
- lib/updateNpm.js
- Improve the footer format.
- Add the used npm version.
> feat: improve pull request body

- dist/index.js
- lib/__tests__/buildPullRequestBody.test.js
- lib/constants.js
- package.json
https://github.com/npm/cli/releases/tag/v6.14.6
> fix: bump npm from 6.14.5 to 6.14.6

- README.md
- action.yml
- dist/index.js
- lib/createOrUpdatePullRequest.js
- lib/index.js
- lib/utils/__tests__/commaSeparatedList.test.js
- lib/utils/commaSeparatedList.js
- package.json
> feat: add labels option

- .github/workflows/release.yml
- package.json
See https://medium.com/swlh/how-to-manually-trigger-a-github-actions-workflow-4712542f1960
> ci: release on actions manually

- dist/index.js
- lib/__tests__/buildPullRequestBody.test.js
- lib/buildPullRequestBody.js
In order to make the packages easier to see.
> feat: split column for repo link in PR body

- dist/index.js
- lib/__tests__/buildPullRequestBody.test.js
- lib/constants.js
- package.json
- https://github.com/npm/cli/releases/tag/v6.14.7
- https://github.com/npm/cli/compare/v6.14.6...v6.14.7
> fix(deps): bump npm from 6.14.6 to 6.14.7

- sider.yml
https://help.sider.review/getting-started/custom-configuration#branchesexclude
> chore: create sider.yml

- .github/workflows/commitlint.yml
- .github/workflows/npm-audit-fix.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- README.md
> feat: change default branch from `master` to `main`

- README.md
- action.yml
- dist/index.js
- lib/createOrUpdatePullRequest.js
- lib/getDefaultBranch.js
- lib/index.js
> feat: set default branch automatically

- dist/index.js
- lib/__tests__/buildCommitBody.test.js
- lib/buildCommitBody.js
- lib/buildPullRequestBody.js
- lib/createOrUpdatePullRequest.js
- lib/index.js
The current commit body is too long (because it is the same as the pull request body).
> feat: improve commit body

- dist/index.js
- lib/__tests__/buildPullRequestBody.test.js
- lib/constants.js
- package.json
- https://github.com/npm/cli/releases/tag/v6.14.8
- https://github.com/npm/cli/compare/v6.14.7...v6.14.8
> fix(deps): bump npm from 6.14.7 to 6.14.8

- .github/workflows/commitlint.yml
- .husky/commit-msg
- .husky/post-commit
- .husky/pre-commit
- dist/index.js
- lib/buildPullRequestBody.js
- lib/utils/advisories.js
- package-lock.json
- package.json
- Apply `ybiq init`.
- Fix ESLint warnings.
> chore(deps-dev): bump all dev dependencies

- dist/index.js
- lib/createOrUpdatePullRequest.js
- lib/getDefaultBranch.js
- lib/updateNpm.js
- lib/utils/splitRepo.js
- scripts/bump-npm.js
- tsconfig.json
See also <https://www.typescriptlang.org/tsconfig>.
> refactor: make code safer via stricter TS config

- sider.yml
https://help.sider.review/getting-started/custom-configuration#ignore
> chore: ignore `dist/` from Sider

- .github/workflows/release.yml
- Remove the `dry-run` input parameter.
> ci(actions): simplify releasing

- .github/workflows/release.yml
See also:
- https://github.com/ybiquitous/npm-audit-fix-action/runs/2268960378
- #364
> fix(actions): fix releasing

- .github/workflows/npm-audit-fix.yml
- .github/workflows/release.yml
- README.md
> chore(release): prepare for v3

- dist/index.js
- lib/__tests__/audit.test.js
- lib/__tests__/fixtures/audit-2.json
- lib/audit.js
> fix: fix an error when `via` is unexpected

- .github/workflows/npm-diff.yml
https://github.com/ybiquitous/npm-diff-action
> ci(actions): introduce ybiquitous/npm-diff-action

- README.md
- action.yml
> feat: update default `labels` parameter

- .github/workflows/npm-audit-fix.yml
- README.md
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
> fix: usage of `workflow_dispatch`

- .github/dependabot.yml
Removing needless time and timezone.
> chore(deps): refactor dependabot.yml

- package.json
> build: require node 12.20.0+

- .github/workflows/release.yml
- README.md
- dist/index.cjs
- lib/constants.js
- package-lock.json
- package.json
BREAKING CHANGE:
npm 9 has some breaking changes, but they may not affect. See the release note:
https://github.com/npm/cli/releases/tag/v9.0.0
> feat!: bump npm from 8 to 9

- README.md
- action.yml
Also documents previously undocumented input and clarifies some descriptions.
Resolves https://github.com/ybiquitous/npm-audit-fix-action/issues/749.
> docs(readme): add action inputs

- .github/workflows/release.yml
- .github/workflows/test.yml
- README.md
- dist/index.cjs
- lib/constants.js
- package-lock.json
- package.json
See https://github.com/npm/cli/releases/tag/v10.0.0
Previous update: #747
> feat!: bump npm from 9 to 10

- README.md
- action.yml
- dist/index.cjs
- lib/npmArgs.js
Usage:
```yaml
- uses: ybiquitous/npm-audit-fix-action@main
with:
npm_args: "--engine-strict=false" 
```
> feat: add `npm_args` input

- .github/workflows/update-dist.yml
> ci(actions): specify PAT to "Update dist" workflow

- .github/workflows/release.yml
- Specify job names for debuggability
- Combine some jobs into one
> ci(actions): improve release workflow

- README.md
- action.yml
- dist/index.cjs
- lib/createOrUpdatePullRequest.js
- lib/index.js
This pull request introduces the ability to assign PR assignees.
> feat: add PR assignees support

- lib/__tests__/aggregateReport.test.js
- lib/__tests__/audit.test.js
- lib/__tests__/buildCommitBody.test.js
- lib/__tests__/buildPullRequestBody.test.js
- lib/__tests__/listPackages.test.js
- lib/__tests__/npmArgs.test.js
- lib/utils/__tests__/commaSeparatedList.test.js
- lib/utils/__tests__/semverToNumber.test.js
- package-lock.json
- package.json
Ref https://nodejs.org/api/test.html
> test: migrate Jest to `node:test`

- .gitattributes
Ref https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
> chore: suppress diffs for generated files in `dist/`

- README.md
- action.yml
- dist/index.cjs
- lib/index.js
This pull request includes changes to add support for specifying a custom path to the project root directory.
> feat: add custom project path support

- dist/index.cjs
- lib/__tests__/buildCommitBody.test.js
- lib/__tests__/buildPullRequestBody.test.js
- lib/buildCommitBody.js
- lib/buildPullRequestBody.js
Too much information could be confusing.
Updated screenshot of #989:
> feat: simplify information on pull request body and commit message

- dist/index.cjs
- lib/__tests__/buildPullRequestBody.test.js
- lib/buildPullRequestBody.js
This pull request includes changes to improve the clarity and consistency of the pull request body message generated by the `buildPullRequestBody` function.
> fix: polish message in pull request body

- action.yml
> fix: prepare for publishing on marketplace

- README.md
> docs(readme): fix latest version from v6 to v7

- .github/workflows/test.yml
- README.md
> test: upload coverage to Codecov

- README.md
- action.yml
To make the descriptions more readable.
> docs: refine input descriptions

- .github/workflows/release.yml
Ref https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables
> ci(actions): improve Git user info in releasing

- .github/workflows/release.yml
Reverts ybiquitous/npm-audit-fix-action#1042
The attempt failed for some reason:
https://github.com/ybiquitous/npm-audit-fix-action/actions/runs/15625409362/job/44018555608
> Revert "ci(actions): use PAT for releasing"

- .github/workflows/release.yml
Ref https://github.com/ybiquitous/.github/blob/f5385aca20bd9b3d63fb5f3da93d8895ff7aa3d2/.github/workflows/action-release-reusable.yml
> ci: introduce reusable release workflow

- .github/workflows/test.yml
It'd be helpful if we could manually trigger the test.
> ci(github): add `workflow_dispatch` trigger to test

- .github/workflows/dependabot-auto-merge.yml
- Pin the used workflow
- Add required permissions
Ref https://github.com/ybiquitous/.github/releases/tag/v1.0.3
> ci: fix auto-merge workflow
