ybiquitous/npm-audit-fix-action

.npmrc
lib/index.js
package.json

This uses the [`engines`](https://docs.npmjs.com/files/package.json#engines) field in `package.json`.
Also, this sets the [`engine-strict`](https://docs.npmjs.com/misc/config#engine-strict) configuration.

feat: read `NPM_VERSION` from `package.json`

---

dist/index.js
lib/__tests__/updateNpm.test.js
lib/updateNpm.js

If `engines.npm` in `package.json` differs from the `NPM_VERSION` constant, the smoke test should fail.

test: remove unneeded `updateNpm.test.js`

---

README.md
action.yml

This changes `chore` to `build`. This convention is according to the following:
- [Conventional Commits](https://www.conventionalcommits.org)
- [Angular](https://github.com/angular/angular/blob/ed1b4a8/CONTRIBUTING.md#type).
> build: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)

feat: change default `commit_title`

---

package.json

The test is unstable on CI (Actions). This aims to avoid the instability as possible.

test: increase timeout value

---

dist/index.js
lib/index.js
lib/packageRepoUrls.js

Currently if a dependency using the `file:`, `git:`, or `github:` protocols then this action fails to work because `npm view` will return a 404 for the dependency.
This is a link to a project which uses the `github:` protocol and shows the action failing to run -- https://github.com/Financial-Times/origami-component-converter/runs/832695920?check_suite_focus=true
My patch makes the github action ignore 404 errors and to surface other errors with their corresponding error message instead of just the exit code.

fix: make file and git dependencies work

---

.github/workflows/commitlint.yml
.github/workflows/npm-audit-fix.yml
.github/workflows/release.yml
.github/workflows/test.yml
goodcheck.yml

See https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/
Also, this change introduces Goodcheck to use the following rule:
https://github.com/sider/goodcheck-rules/blob/cf63d780b5a8c21ec908a0c871c99a4a10a18747/rules/github.yml#L1

ci(actions): use `$default-branch` macro

---

.github/workflows/test.yml
README.md
action.yml
dist/index.js
lib/index.js

BREAKING CHANGE: `with.github_token` is no longer required and `env.GITHUB_TOKEN` is ignored.

feat: add `github_token` default and remove `env.GITHUB_TOKEN`

---

dist/index.js
lib/__tests__/buildPullRequestBody.test.js
lib/constants.js
package.json

Via `$ npm run npm:version 6.14.11`.
- https://github.com/npm/cli/releases/tag/v6.14.11
- https://github.com/npm/cli/compare/v6.14.8...v6.14.11

fix(deps): bump npm from 6.14.8 to 6.14.11

---

.github/workflows/update-dist.yml

ci(actions): change trigger event for `update-dist`

---

dist/index.js
lib/index.js

For some reason, it is necessary to re-run `npm ci` after `npm audit fix`.

fix: re-run `npm ci` for more accurate diff list

---

dist/index.js
lib/auditFix.js

`npm audit fix` can return code `1` when no fix available.

fix: ignore return code of `npm audit fix`

---

dist/index.js
lib/auditFix.js

fix: output warning when `npm audit fix` returns non-zero

---

dist/index.cjs
lib/__tests__/__snapshots__/aggregateReport.test.js.snap
lib/__tests__/aggregateReport.test.js
lib/__tests__/buildPullRequestBody.test.js
lib/__tests__/fixtures/empty_package.json/package-lock.json
lib/__tests__/fixtures/noversion_package.json/package-lock.json
lib/__tests__/fixtures/report.json
lib/__tests__/listPackages.test.js
lib/aggregateReport.js
lib/buildPullRequestBody.js
lib/listPackages.js
lib/types.d.ts
lib/utils/splitPackageName.js
lib/utils/splitRepo.js

This change aims to fix the following case when the same packages has different locations.
```
node_modules/svgo/node_modules/css-select:css-select@3.1.2
node_modules/css-select:css-select@4.1.3
```

fix: sub dependencies

---

.github/workflows/npm-audit-fix.yml
.github/workflows/test.yml
README.md

This PR fixes the following error:
```
...
/usr/bin/git push ***github.com/ybiquitous/npm-audit-fix-action.git HEAD:npm-audit-fix-action/fix --force
remote: Permission to ybiquitous/npm-audit-fix-action.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/ybiquitous/npm-audit-fix-action.git/': The requested URL returned error: 403
Error: The process '/usr/bin/git' failed with exit code 128
```
https://github.com/ybiquitous/npm-audit-fix-action/actions/runs/3825821567/jobs/6509083089#step:3:2931

fix: `permissions.contents` from `read` to `write`

---

.github/workflows/test.yml
.npmrc

Dependabot uses Node.js 16.20.1 and npm 8.19.4, so `engine-strict=true` in `.npmrc` fails Dependabot.
See https://github.com/ybiquitous/npm-audit-fix-action/network/updates/689567062

chore: enable `engine-strict` only on CI

---

dist/index.cjs
lib/index.js

By default, `exec()` tries using the pre-installed Node.js instead of `runs` in `action.yml`.
This change fixes the bug by adding `runs` Node.js path to the `PATH` environment variable.

fix: running Node.js version when using `exec()`

---

package-lock.json
package.json
tsconfig.json

In addition, it partially refers to https://github.com/tsconfig/bases/blob/031273b815ff7f672c7c9057fb7d19ef363054b1/bases/node20.json

chore: simplify `tsconfig.json` thanks to `@tsconfig/strictest`

---

dist/index.cjs
lib/createOrUpdatePullRequest.js

Fixes #884
Before:
When a PR was closed but the PR's branch (e.g. `npm-audit-fix-action/fix`) was not deleted,
pushing a new branch (but the same name) fails.
After:
Even if a PR was closed, this change always tries overwriting the PR's branch.
If a branch is not created yet, creating a branch passes as before.

fix: always overwrite branch even if PR were already closed

---

.github/dependabot.yml

Closes #900
To prevent CI errors like <https://github.com/ybiquitous/npm-audit-fix-action/actions/runs/9947237051/job/27479486904?pr=900#step:5:5>.

chore(deps): temporarily disable ESLint major updates for Dependabot

---

dist/index.cjs
lib/constants.js
package-lock.json
package.json

npm v11.0.0 was released on 2024-12-16.
Ref https://github.com/npm/cli/releases/tag/v11.0.0
The previous update:
- #834

feat!: bump npm from 10 to 11

---

.github/workflows/release.yml

PR #981 will be released as v7 (the next major version).

ci: prepare for v7 release

---

.github/workflows/release.yml

This PR will not need any more input.

ci: auto-determine major version tag on release workflow

---

dist/index.cjs
lib/__tests__/buildPullRequestBody.test.js
lib/buildPullRequestBody.js
lib/index.js

Ref the default environment variables for GitHub Actions:
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables
---
Test with the PR #989 body:

feat: add action run link to generated pull request body

---

dist/index.cjs
lib/createOrUpdatePullRequest.js

This enables people to move from an action run page to a pull request page more easily.
Ref https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-a-notice-message
---
Test:
https://github.com/ybiquitous/npm-audit-fix-action/actions/runs/13381286320?pr=990

feat: show notice message for generated pull requests

---

dist/index.cjs
lib/__tests__/buildPullRequestBody.test.js
lib/buildPullRequestBody.js

Linebreaks make a table in a pull request body hard to view.

fix: prevent linebreaks between versions in pull request body's table

---

dist/index.cjs
lib/__tests__/buildPullRequestBody.test.js
lib/buildPullRequestBody.js

The following table could be hard to view (#989):

fix: prevent too long column in pull request body's table

---

package.json
tsconfig.json

Change summary:
- Move `--noEmit` to `tsconfig.json`.
- Update `target` and `module` in `tsconfig.json` to follow newer Node.js versions.

chore: refine TypeScript configuration

---

dist/index.js
lib/createOrUpdatePullRequest.js

Hello,
As shown in the Action logs, there are cases where only the `package.json` file is updated, but currently, the program only stages `package-lock.json` for commit.
This leads to issues when we attempt to commit without having staged any files.
This PR addresses the problem by adding the `package.json` before committing.
Thanks!

fix: also commit `package.json`

---

README.md
action.yml

Including `github.actor_id` is closer to actual commits.
Ref https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context

feat: change `github_email` input default to include `github.actor_id`
